#Welcome to GenesisMC!
#Plugin created by Dueris

config-version: 151668

#DO NOT CHANGE THE CONFIG VERSION.
#If you get an error in console about it being the wrong version, delete all GenesisMC files and restart the server to apply new config options.
#If they aren't loaded correctly, many things could break

#ENJOY!!!