bootstrapper: me.dueris.genesismc.Bootstrap
loader: me.dueris.genesismc.DependencyLoader
load: POSTWORLD
name: GenesisMC
version: 'mc1.20-0.2.8'
main: me.dueris.genesismc.GenesisMC
api-version: '1.20'
authors: [ Dueris, Tye ]
folia-supported: true
description: Bringing the life and fun of the Origins mod to PaperMC
website: https://ko-fi.com/dueris
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: AFTER
      required: false
    Floodgate:
      load: AFTER
      required: false
    SkinsRestorer:
      load: BEFORE
      required: false
