
name: Publish to GitHub Packages

on:
  push:
    branches:
      - origin  # Adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-openj9', 'adopt-hotspot')

      - name: Build and Publish
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew publish

        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Updated to use GIT_TOKEN

      - name: Install Cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli
        env:
          PIP_NO_CACHE_DIR: "false"

      - name: Check for POM file and List Files
        run: |
          echo "Checking for POM file..."
          if [ -f "mainPlugin/mc1.20-v0.2.2/mainPlugin-mc1.20-v0.2.2.pom" ]; then
            echo "POM file found!"
          else
            echo "POM file not found."
          fi

          if [ -f "mainPlugin/mc1.20-v0.2.2/" ]; then
            echo "folder file found!"
          else
            echo "folder file not found."
          fi

          # Print the names of files within the mainPlugin directory
          echo "Contents of the mainPlugin directory:"
          ls -R mainPlugin

        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}  # Replace with your Cloudsmith API Key
