name: Build and Archive Jars

on:
  push:
    branches:
      - origin  # Change this to your branch name if it's called "origin"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    
    - name: Build the project
      run: ./gradlew build  # Replace with your build command
    
    - name: Archive Jars
      run: |
        commit_hash=$(git rev-parse --short HEAD)
        mkdir -p builds/commits/
        jar_files=$(find build/libs -name "*.jar")
        zip -j builds/commits/${commit_hash}.zip ${jar_files}
      shell: bash

    - name: Commit and Push Archive
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add builds/commits/${commit_hash}.zip
        git commit -m "Add archive for commit ${commit_hash}"
        git push
