
name: Publish to GitHub Packages

on:
  push:
    branches:
      - origin  # Adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-openj9', 'adopt-hotspot')

      - name: Build and Publish
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew publish

        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Updated to use GIT_TOKEN

      - name: Install Cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli
        env:
          PIP_NO_CACHE_DIR: "false"

      - name: Prepare POM
        run: |
          echo "POM-PRINT-START"

          # Print the POM file
          echo "Generated Pom file:"
          cat mainPlugin/build/publications/maven/pom-default.xml

        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}  # Replace with your Cloudsmith API Key
          
      - name: Push to Cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'maven'
          owner: 'genesismc'               # Your Cloudsmith organization name
          repo: 'genesismc'               # Your Cloudsmith Repository name (slug)
          pom-file: 'mainPlugin/build/publications/maven/pom-default.xml'  # Path to your .pom file
          republish: 'true'            # Set to 'true' ONLY if version is not changing
          file: 'mainPlugin/build/libs/mainPlugin-mc1.20-v0.2.2.jar'  # Path to your Maven artifact (JAR file)
