name: Build and Archive Jars

on:
  push:
    branches:
      - origin  # Change this to your branch name if it's called "origin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build the project
      run: ./gradlew build  # Replace with your build command

    - name: Archive Jars
      run: |
        commit_hash=$(git rev-parse --short HEAD)
        jar_files=$(find build/libs -name "*.jar")
        if [ -n "$jar_files" ]; then
          zip -j specified_directory/${commit_hash}.zip ${jar_files}
        fi
      shell: bash

    - name: Commit and Push Archive
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        commit_hash=$(git rev-parse --short HEAD)
        if [ -f "specified_directory/${commit_hash}.zip" ]; then
          git add specified_directory/${commit_hash}.zip
          git commit -m "Add archive for commit ${commit_hash}"
          git push origin HEAD:${{ github.ref }}
        fi

    - name: Notify Discord
      if: ${{ (success() || failure()) }}
      uses: Tim203/actions-git-discord-webhook@70f38ded3aca51635ec978ab4e1a58cd4cd0c2ff
      with:
        webhook_url: https://discord.com/api/webhooks/1081276038983721070/_0mh9jU8_ZIf0grfDqdSinlQo2ZbTWPii_AiY-it13Nybp9z5jqgOzP9b6tKMmUx03JN
        status: ${{ job.status }}
