name: Publish to GitHub Packages

on:
  push:
    branches:
      - origin  # Adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-openj9', 'adopt-hotspot')

      - name: Build
        run: |
          ./gradlew build
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Updated to use GIT_TOKEN

      - name: Install Cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli
        env:
          PIP_NO_CACHE_DIR: "false"

      - name: Check for POM files in Gradle cache
        run: |
          echo "Checking for POM files in Gradle cache..."
          find $HOME/.gradle/caches -type f -name "*.pom" | while read pomfile; do
            echo "Found POM file: $pomfile"
          done || echo "No POM files found"
        shell: bash
