name: Build and Publish

on:
  push:
    branches:
      - origin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17 with AdoptOpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set environment variables
        run: |
          echo "CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}" >> $GITHUB_ENV
          echo "CLOUDSMITH_USERNAME=${{ secrets.CLOUDSMITH_USERNAME }}" >> $GITHUB_ENV
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          export CLOUDSMITH_USERNAME=${{ secrets.CLOUDSMITH_USERNAME }}

      - name: Build and Publish
        run: |
          chmod +x ./gradlew
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          export CLOUDSMITH_USERNAME=${{ secrets.CLOUDSMITH_USERNAME }}
          ./gradlew build
          ./gradlew publish
