name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - origin

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed

      - name: Build
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: |
          echo "Publishing to GitHub Packages"
          echo "registry=https://npm.pkg.github.com/Dueris" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          gh release create v0.2.2 build/libs/genesis-standalone-mc1.20-v0.2.2.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
