name: Publish to PackageCloud

on:
  push:
    branches:
      - origin

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Build
        run: ./gradlew build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # Choose the Ruby version you need

      - name: Install required gem (package_cloud)
        run: gem install package_cloud

      - name: Publish to PackageCloud
        run: |
          package_cloud push username/reponame/java /path/to/package.jar --coordinates=com.mygroup:packagename:1.0.2
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
