name: Publish Gradle Plugin

on:
  push:
    branches:
      - origin # Replace with your target branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Navigate to Subproject Directory
        run: cd mainPlugin

      - name: Publish to Gradle Plugin Portal
        run: |
          ./gradlew publishPlugins --validate-only
          ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
